/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const InquiryStatus = IDL.Variant({
  'New' : IDL.Null,
  'Contacted' : IDL.Null,
  'InReview' : IDL.Null,
  'Fulfilled' : IDL.Null,
});
export const OrderDetails = IDL.Record({
  'iceType' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'deliveryFrequency' : IDL.Opt(IDL.Text),
  'desiredDeliveryDays' : IDL.Vec(IDL.Text),
  'deliveryTimeWindow' : IDL.Opt(IDL.Text),
  'estimatedWeeklyUsage' : IDL.Opt(IDL.Text),
  'businessName' : IDL.Opt(IDL.Text),
  'totalBags' : IDL.Opt(IDL.Text),
  'message' : IDL.Opt(IDL.Text),
  'onSiteFreezer' : IDL.Opt(IDL.Bool),
  'venueName' : IDL.Opt(IDL.Text),
  'eventDate' : IDL.Opt(IDL.Text),
});
export const InquiryType = IDL.Variant({
  'Event' : IDL.Null,
  'General' : IDL.Null,
  'Wholesale' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'orderDetails' : OrderDetails,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'businessName' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'exportInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
  'isAuthenticated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setupPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Nat], []),
  'updateInquiryStatus' : IDL.Func(
      [IDL.Nat, InquiryStatus, IDL.Opt(IDL.Text)],
      [IDL.Opt(Inquiry)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const InquiryStatus = IDL.Variant({
    'New' : IDL.Null,
    'Contacted' : IDL.Null,
    'InReview' : IDL.Null,
    'Fulfilled' : IDL.Null,
  });
  const OrderDetails = IDL.Record({
    'iceType' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'deliveryFrequency' : IDL.Opt(IDL.Text),
    'desiredDeliveryDays' : IDL.Vec(IDL.Text),
    'deliveryTimeWindow' : IDL.Opt(IDL.Text),
    'estimatedWeeklyUsage' : IDL.Opt(IDL.Text),
    'businessName' : IDL.Opt(IDL.Text),
    'totalBags' : IDL.Opt(IDL.Text),
    'message' : IDL.Opt(IDL.Text),
    'onSiteFreezer' : IDL.Opt(IDL.Bool),
    'venueName' : IDL.Opt(IDL.Text),
    'eventDate' : IDL.Opt(IDL.Text),
  });
  const InquiryType = IDL.Variant({
    'Event' : IDL.Null,
    'General' : IDL.Null,
    'Wholesale' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'orderDetails' : OrderDetails,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'businessName' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'exportInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
    'isAuthenticated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setupPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Nat], []),
    'updateInquiryStatus' : IDL.Func(
        [IDL.Nat, InquiryStatus, IDL.Opt(IDL.Text)],
        [IDL.Opt(Inquiry)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };