/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Inquiry {
  'id' : bigint,
  'status' : InquiryStatus,
  'orderDetails' : OrderDetails,
  'inquiryType' : InquiryType,
  'name' : string,
  'businessName' : [] | [string],
  'email' : string,
  'address' : [] | [string],
  'notes' : [] | [string],
  'timestamp' : bigint,
  'phone' : string,
}
export type InquiryStatus = { 'New' : null } |
  { 'Contacted' : null } |
  { 'InReview' : null } |
  { 'Fulfilled' : null };
export type InquiryType = { 'Event' : null } |
  { 'General' : null } |
  { 'Wholesale' : null };
export interface OrderDetails {
  'iceType' : [] | [string],
  'deliveryAddress' : [] | [string],
  'deliveryFrequency' : [] | [string],
  'desiredDeliveryDays' : Array<string>,
  'deliveryTimeWindow' : [] | [string],
  'estimatedWeeklyUsage' : [] | [string],
  'businessName' : [] | [string],
  'totalBags' : [] | [string],
  'message' : [] | [string],
  'onSiteFreezer' : [] | [boolean],
  'venueName' : [] | [string],
  'eventDate' : [] | [string],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'exportInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiry' : ActorMethod<[bigint], [] | [Inquiry]>,
  'isAuthenticated' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], [] | [string]>,
  'logout' : ActorMethod<[string], undefined>,
  'schema' : ActorMethod<[], string>,
  'setupPassword' : ActorMethod<[string], boolean>,
  'submitInquiry' : ActorMethod<[Inquiry], bigint>,
  'updateInquiryStatus' : ActorMethod<
    [bigint, InquiryStatus, [] | [string]],
    [] | [Inquiry]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];